pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image '3.9.16-eclipse-temurin-11-alpine' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:26-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
