pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.9.1-eclipse-temurin-11-alpine' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'alpine:latest' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
